# pandas 数据分析库

```sh
#安装 pandas
pip install pandas
```

In [1]:
import numpy as np
import pandas as pd

## 数据结构

### 一维 Series

In [2]:
pd.Series(data = [1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
# 不指定索引，使用默认索引，从 0 开始
pd.Series(data = [2, 4, 5, 9])

0    2
1    4
2    5
3    9
dtype: int64

### 二维 DataFrame

In [4]:
pd.DataFrame(data = np.random.randint(0, 100, size = (5, 3)),
            columns=['Python', 'English', 'Math'],
            index=list('ABCDE'),
            dtype=np.float32)

   Python  English  Math
A    44.0     84.0   4.0
B     2.0     33.0  29.0
C    29.0     24.0  62.0
D    81.0     61.0   1.0
E    50.0     51.0  80.0

**另一种创建方式**

In [5]:
pd.DataFrame(data = {
    'Python': np.random.randint(0, 100, size=5),
    'English': np.random.randint(0, 100, size=5),
    'Math': np.random.randint(0, 100, size=5),
}, index = list('ABCDE'), dtype = np.float32)

   Python  English  Math
A    23.0     11.0  59.0
B    35.0     52.0  29.0
C    40.0     10.0  33.0
D    30.0     71.0  30.0
E    11.0     69.0  67.0

## 数据查看

In [6]:
df = pd.DataFrame(data = np.random.randint(0, 100, size = (150, 3)),
            columns=['Python', 'English', 'Math'],
            dtype=np.float32)

In [7]:
df

     Python  English  Math
0      32.0     91.0   5.0
1      95.0     15.0  77.0
2      99.0     13.0  20.0
3      78.0     86.0  98.0
4      57.0     75.0  18.0
..      ...      ...   ...
145    33.0     49.0  76.0
146    17.0     44.0  50.0
147    10.0     46.0  12.0
148    48.0     51.0   3.0
149    74.0     17.0  64.0

[150 rows x 3 columns]

In [8]:
#查看形状
df.shape

(150, 3)

In [9]:
#显示前 10 个，如果不指定数字，默认为 5 个
df.head(10)

   Python  English  Math
0    32.0     91.0   5.0
1    95.0     15.0  77.0
2    99.0     13.0  20.0
3    78.0     86.0  98.0
4    57.0     75.0  18.0
5    32.0     16.0  58.0
6    23.0     30.0  26.0
7    59.0     57.0  56.0
8    16.0     35.0  55.0
9    69.0     16.0  44.0

In [10]:
# 默认查看后 5 个，可以指定数字
df.tail()

     Python  English  Math
145    33.0     49.0  76.0
146    17.0     44.0  50.0
147    10.0     46.0  12.0
148    48.0     51.0   3.0
149    74.0     17.0  64.0

In [11]:
df.dtypes

Python     float32
English    float32
Math       float32
dtype: object

In [12]:
#修改 Python 列类型
df['Python'] = df['Python'].astype(np.int64)

df.dtypes

Python       int64
English    float32
Math       float32
dtype: object

In [13]:
#获取行索引
df.index

RangeIndex(start=0, stop=150, step=1)

In [14]:
#获取列索引
df.columns

Index(['Python', 'English', 'Math'], dtype='object')

In [15]:
#查看 df 中的 ndarray。这里可以推断 pandas 是基于 numpy 开发的
type(df.values)

numpy.ndarray

In [16]:
df.values.shape

(150, 3)

In [17]:
#查看数值型列的统计信息，属性有 计数、平均值、标准差、最小值、四分位数、中位数、最大值
df.describe()

           Python     English        Math
count  150.000000  150.000000  150.000000
mean    52.233333   49.720001   50.586666
std     28.160236   28.377163   29.274719
min      1.000000    1.000000    1.000000
25%     30.250000   25.500000   23.000000
50%     50.500000   49.000000   51.500000
75%     76.750000   75.000000   75.750000
max     99.000000   99.000000   99.000000

In [18]:
#查看列索引、数据类型、非空计数、内存信息
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Python   150 non-null    int64
 1   English  150 non-null    float32
 2   Math     150 non-null    float32
dtypes: float32(2), int64(1)
memory usage: 2.5 KB

## 数据加载与持久化

### csv 格式

In [19]:
df = pd.DataFrame(data = np.random.randint(0, 50, size = (50, 5)),
               columns = ['IT', '化工', '生物', '教师', '土木'])
df.head()

   IT  化工  生物  教师  土木
0  37  38  21  25  18
1  46  10  30  32  49
2   7  40  16  36  29
3  39  45  29  39   3
4   2  39  16  31  47

In [20]:
# 持久化到 csv 文件
#   sep: 分隔符，默认为英文逗号
#   header: 是否保存列索引
#   index: 是否保存行索引。文件被加载时，默认的行索引会被作为一列
df.to_csv('salary.csv', sep=':', header=True, index=True)

salary.csv 前几行数据：
```
:IT:化工:生物:教师:土木
0:30:38:23:48:10
1:10:31:3:37:11
2:16:41:28:26:42
3:36:39:1:47:34
4:14:38:8:2:7
```

In [21]:
# 读取 csv 文件
#   sep: 指定分隔符
#   header: 指定列索引
#   index_col: 指定行索引
df2 = pd.read_csv('salary.csv', sep=':', header=[0], index_col=0)
df2.head()

   IT  化工  生物  教师  土木
0  37  38  21  25  18
1  46  10  30  32  49
2   7  40  16  36  29
3  39  45  29  39   3
4   2  39  16  31  47

### excel 格式

In [22]:
df1 = pd.DataFrame(data = np.random.randint(0, 50, size = (50, 5)),
               columns = ['IT', '化工', '生物', '教师', '土木'])

df.head()

   IT  化工  生物  教师  土木
0  37  38  21  25  18
1  46  10  30  32  49
2   7  40  16  36  29
3  39  45  29  39   3
4   2  39  16  31  47

In [23]:
df1.to_excel('salary1.xlsx',
            sheet_name='salary', # 工作表名
            header=True, # 导出列索引
            index=False) # 不导出行索引

# 读取 xlsx 文件
res = pd.read_excel('salary1.xlsx',
            sheet_name=0, #读取第一个工作表。也可以直接指定名字 'salary'
            header=0, # 使用第一行数据作为列索引
            names=list('ABCDE'), #替换列索引
            # index_col=0 # 指定哪一列作为行索引。默认使用自然索引。如果导出了行索引，可设置为 0 使用它
                   )

res.head()

    A   B   C   D   E
0  19   3  22  33  44
1  10  46  28  44  40
2   9  33  27  13  35
3  34   9  21  28  17
4  41  15  21  14  37

**同时导出多个工作表**

In [24]:
df1 = pd.DataFrame(data = np.random.randint(0, 50, size = (50, 5)),
               columns = ['IT', '化工', '生物', '教师', '土木'])
df2 = pd.DataFrame(data = np.random.randint(0, 50, size = (150, 3)),
               columns = ['Tensorflow', 'Pytorch', 'Keras'])

In [25]:
with pd.ExcelWriter('salary2.xlsx') as w:
    df1.to_excel(w, sheet_name='salary', index=False)
    df2.to_excel(w, sheet_name='score', index=False)

In [26]:
df3 = pd.read_excel('salary2.xlsx', sheet_name='score')
df3.head()

   Tensorflow  Pytorch  Keras
0           8       30      5
1          18       21     29
2          27       31      5
3          16       48     29
4          17       11     35

In [27]:
df4 = pd.read_excel('salary2.xlsx', sheet_name='salary')
df4.head()

   IT  化工  生物  教师  土木
0  24  30   0  21  24
1  25  43  31  10  35
2  23  22  30  47   3
3  39  14  35  46  11
4  38  24  43  23  18

### 其他格式

sql、HDFS 等

## 数据选择

和 numpy 的花式索引类似

In [28]:
df = pd.DataFrame(np.random.randint(0, 150, size=(1000, 3)),
                  columns=['Python', 'English', 'Math'])
df.head()

   Python  English  Math
0     138      113   113
1     124        0   117
2     127       66    22
3      16       77    54
4     142       76    13

**列选取**

In [29]:
#获取某一列，得到的数据类型为 Series
df['Python']

0      138
1      124
2      127
3       16
4      142
      ...
995    109
996      3
997    132
998     53
999     52
Name: Python, Length: 1000, dtype: int64

In [30]:
df.Math

0      113
1      117
2       22
3       54
4       13
      ...
995     61
996      1
997     14
998    133
999    104
Name: Math, Length: 1000, dtype: int64

In [31]:
#同时获取多列，得到的是 DataFrame 对象
df[['English', 'Math']]

     English  Math
0        113   113
1          0   117
2         66    22
3         77    54
4         76    13
..       ...   ...
995      107    61
996      106     1
997       77    14
998       71   133
999      149   104

[1000 rows x 2 columns]

**行选取**

In [32]:
df2 = pd.DataFrame(np.random.randint(0, 150, size=(5, 3)),
                  columns=['Python', 'English', 'Math'],
                  index=list('ABCDE'))
df2

   Python  English  Math
A      98       49    15
B      41        0    71
C     111       54   103
D      65       94     5
E     133       96   127

In [33]:
#获取某一行
df2.loc['A']

Python     98
English    49
Math       15
Name: A, dtype: int64

In [34]:
#获取多行
df2.loc[['A', 'D']]

   Python  English  Math
A      98       49    15
D      65       94     5

In [35]:
#通过整数来索引第一行
df2.iloc[0]

Python     98
English    49
Math       15
Name: A, dtype: int64

In [36]:
#通过整数来索引多行
df2.iloc[[0, 1]]

   Python  English  Math
A      98       49    15
B      41        0    71

**获取具体坐标的数值**

In [37]:
df2['Math']['B']

71

In [38]:
df2.loc['B']['Math']

71

In [39]:
df2.loc['B', 'Math']

71

In [40]:
df2.loc['B'].Math

71

In [41]:
print(df2.iloc[1]['Math'])
print(df2.iloc[1].Math)
print(df2.iloc[1, 2])

71
71
71

In [42]:
#指定多行的指定列
df2.loc[['A','C']]['English']
#df2.loc[['A','C'], 'English']
#df2.loc[['A','C']].English

A    49
C    54
Name: English, dtype: int64

In [43]:
#指定多行的指定多列
df2.loc[['A','C']][['English', 'Math']]
#df2.loc[['A','C'], ['English', 'Math']]

   English  Math
A       49    15
C       54   103

**切片**

In [44]:
df2.loc['A':'C']

   Python  English  Math
A      98       49    15
B      41        0    71
C     111       54   103

In [45]:
df2.iloc[0:3]

   Python  English  Math
A      98       49    15
B      41        0    71
C     111       54   103

In [46]:
#指定多行的指定多列
#df2.loc['C':][['English', 'Math']]
#df2.loc['C':, ['English', 'Math']]

df2.iloc[2:][['English', 'Math']]

   English  Math
C       54   103
D       94     5
E       96   127

**布尔索引**

In [47]:
df = pd.DataFrame(np.random.randint(0, 150, size=(1000, 3)),
                  columns=['Python', 'English', 'Math'])

# Python 零分的条件
cond = df['Python'] == 0
cond

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Python, Length: 1000, dtype: bool

In [48]:
df[cond]

     Python  English  Math
134       0      107    95
210       0       62   125
301       0      110    59
645       0       55    32
831       0      117    84
884       0       28    80

In [49]:
cond1 = df['Python'] > 140
cond2 = df['Math'] > 140
cond3 = df['English'] > 140
cond = cond1 & cond2 & cond3
df[cond]

     Python  English  Math
204     145      143   148

**赋值操作**

In [78]:
#一维序列，表示 10 个学生的 Pytorch 成绩
s = pd.Series(np.random.randint(0, 150, size=10),
              index=list('ABCDEFGHIJ'),
              name='Pytorch')

#二维数组，表示学生成绩
df = pd.DataFrame(np.random.randint(0, 150, size=(10, 3)),
                  index=list('ABCDEFGHIJ'),
                  columns=['Pandas', 'Tensorflow', 'Keras'])
df.head()

   Pandas  Tensorflow  Keras
A      45         115    101
B      95          25     91
C      54          68     32
D     107          43     91
E     116           5     98

In [79]:
df['Java'] = np.random.randint(0, 100, size = 10)
df.head()

   Pandas  Tensorflow  Keras  Java
A      45         115    101    55
B      95          25     91    37
C      54          68     32    30
D     107          43     91    17
E     116           5     98    91

In [80]:
#增加一列，会根据行索引自动对齐
df['Pytorch'] = s
df.head()

   Pandas  Tensorflow  Keras  Java  Pytorch
A      45         115    101    55       66
B      95          25     91    37      135
C      54          68     32    30      104
D     107          43     91    17       58
E     116           5     98    91       91

In [88]:
#按标签赋值
df.loc['A', 'Pytorch'] = 150

#按位置赋值
df.iloc[1, 2] = 150

df.head()

   Pandas  Tensorflow  Keras  Java  Pytorch
A      45         115    101    55      150
B      95          25    150    37      135
C      54          68     32   100      104
D     107          43     91   100       58
E     116           5     98    91       91

In [91]:
#对某一列进行赋值
#df.loc[:, 'Pandas'] = 10
df.loc[:, 'Pandas'] = np.array([100] * 10)
df.head()

   Pandas  Tensorflow  Keras  Java  Pytorch
A     100         115    101    55      150
B     100          25    150    37      135
C     100          68     32   100      104
D     100          43     91   100       58
E     100           5     98    91       91

In [76]:
#对某一行进行赋值
#df.iloc[0] = 92
df.iloc[0] = np.array([92] * 5)
df.head()

   Pandas  Tensorflow  Keras  Java  Pytorch
A      92          92     92    92       92
B     100          40    150    69      115
C     100         109     60    66       96
D     100          68     79    75       14
E     100         127      4     1      104

In [77]:
cond = df < 92
df[cond] = 92
df.head()

   Pandas  Tensorflow  Keras  Java  Pytorch
A      92          92     92    92       92
B     100          92    150    92      115
C     100         109     92    92       96
D     100          92     92    92       92
E     100         127     92    92      104

## 练习 1

1

创建 1000 条语文、数学、英语、Python 的考试成绩 DataFrame，最高分为 150，分别将数据保存到 csv 文件和 excel 文件，保存时不保存行索引

In [56]:
df = pd.DataFrame(np.random.randint(0, 151, size=(1000, 4)),
                  columns=['语文', '数学', '英语', 'Python'])
df.head()

   语文   数学   英语  Python
0  64   96   30      54
1  22   79  140      12
2  10   86  129     149
3  41   80   57      35
4  79  112   91     141

In [57]:
df.to_csv('scores.csv', index=False, header=True)
df.to_excel('scores.xlsx', index=False, header=True)

2

使用字典创建 DataFrame，行索引为 a\~z，列索引是身高（160\~185）、体重（50\~90）、学历（无、本科、硕士、博士）
身高和体重使用 Numpy 随机生成，学历数据先创建数组 `edu=np.array(["无","本科","硕士","博士"])`，然后使用花式索引从四个数据中选择 26 个数据

In [58]:
edu = np.array(["无","本科","硕士","博士"])
random_idx = np.random.randint(0, 4, size = 26)
edu[random_idx]

array(['硕士', '博士', '无', '本科', '硕士', '无', '博士', '无', '博士', '硕士', '无', '本科',
       '无', '本科', '博士', '无', '博士', '本科', '本科', '硕士', '硕士', '本科', '本科',
       '硕士', '硕士', '博士'], dtype='<U2')

In [59]:
import string

df = pd.DataFrame(data = {
                    'height': np.random.randint(160, 186, size=26),
                    'weight': np.random.randint(50, 91, size=26),
                    'education': edu[random_idx],
                    }, 
                  index=[letter for letter in string.ascii_lowercase])
df.head()

   height  weight education
a     175      60        硕士
b     167      68        博士
c     171      90         无
d     164      57        本科
e     165      73        硕士

3

使用题目 2 中的数据进行筛选：
1) 筛选索引大于 't' 的所有数据
2) 筛选学历为博士，身高大于 170 或体重小于 80 的学生

In [60]:
df.loc['t':]

   height  weight education
t     175      79        硕士
u     160      65        硕士
v     171      76        本科
w     166      70        本科
x     179      86        硕士
y     177      59        硕士
z     185      87        博士

In [61]:
cond1 = df['education'] == '博士'
cond2 = df['weight'] < 80
cond3 = df['height'] > 170
cond = cond1 & cond2 & cond3
df[cond]

   height  weight education
g     184      62        博士

4

对题目 2 中的数据进行修改
1) 本科生减肥，减掉体重 10
2) 博士生减肥，减掉体重范围是 5~10

In [62]:
cond = df['education'] == '本科'
df.loc[cond]

   height  weight education
d     164      57        本科
l     172      90        本科
n     185      82        本科
r     169      68        本科
s     174      83        本科
v     171      76        本科
w     166      70        本科

In [63]:
df.loc[cond, 'weight'] -= 10
df.loc[cond]

   height  weight education
d     164      47        本科
l     172      80        本科
n     185      72        本科
r     169      58        本科
s     174      73        本科
v     171      66        本科
w     166      60        本科

In [64]:
cond = df['education'] == '博士'
df.loc[cond]

   height  weight education
b     167      68        博士
g     184      62        博士
i     169      80        博士
o     168      64        博士
q     167      59        博士
z     185      87        博士

In [65]:
df[cond].shape[0]

6

In [66]:
arr = np.random.randint(5, 11, size=df[cond].shape[0])
arr

array([ 8,  6, 10,  7,  6,  7])

In [67]:
#两个数组相减
df.loc[cond, 'weight'] -= arr

In [68]:
df.loc[cond]

   height  weight education
b     167      60        博士
g     184      56        博士
i     169      70        博士
o     168      57        博士
q     167      53        博士
z     185      80        博士